// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjXpilP5nC59189eEoJhtYBrhnPTFNiIE',
    appId: '1:311270227237:web:34c02ee5666c08a7686ecc',
    messagingSenderId: '311270227237',
    projectId: 'hospital-da9b0',
    authDomain: 'hospital-da9b0.firebaseapp.com',
    storageBucket: 'hospital-da9b0.firebasestorage.app',
    measurementId: 'G-LPWJLT8K10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw_AKu2H8eZF4eibh8_cT-rVW7kPOKg7o',
    appId: '1:311270227237:android:fa6eddd065fb125f686ecc',
    messagingSenderId: '311270227237',
    projectId: 'hospital-da9b0',
    storageBucket: 'hospital-da9b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2qkHqZ5JkwjFYuCwoQVdlSWxHnmGNwBg',
    appId: '1:311270227237:ios:9e97907d5daf6f0b686ecc',
    messagingSenderId: '311270227237',
    projectId: 'hospital-da9b0',
    storageBucket: 'hospital-da9b0.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2qkHqZ5JkwjFYuCwoQVdlSWxHnmGNwBg',
    appId: '1:311270227237:ios:9e97907d5daf6f0b686ecc',
    messagingSenderId: '311270227237',
    projectId: 'hospital-da9b0',
    storageBucket: 'hospital-da9b0.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjXpilP5nC59189eEoJhtYBrhnPTFNiIE',
    appId: '1:311270227237:web:444ba35e744f7a30686ecc',
    messagingSenderId: '311270227237',
    projectId: 'hospital-da9b0',
    authDomain: 'hospital-da9b0.firebaseapp.com',
    storageBucket: 'hospital-da9b0.firebasestorage.app',
    measurementId: 'G-040LD0HBG9',
  );
}
